[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "polyopening"
version = "0.1.0"
description = "A tool to determine the opening angle of coordination polyhedra"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
authors = [
    { name = "Lukas Hueckmann" },
]

dependencies = [
    "numpy>=2.0",
    "ase>=3.25.0",
    "qc-grid>=0.0.9",
    "scipy<=1.16.2",
]

classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/lhuckmann/polyopening"
Repository = "https://github.com/lhuckmann/polyopening"

[tool.setuptools.packages.find]
where = ["src"]
